---
title: "Data Visualisation"
author: "Simon Gendrisch"
format: html
---


```{r, output = F}
library(tidyverse)
library(sf)
library(tibble)
library(rnaturalearth)
library(stringr)
library(tidyr)
library(patchwork)
library(ggspatial)
library(prettymapr)
library(maptiles)
library(tidyterra)


```

```{r, output = F}

survey_data <- read_csv("data/GIS/test/observations_filled.csv")

survey_data %>% 
  filter(species == "sperm_whale")

survey_data <- survey_data %>% 
  st_as_sf(wkt = "geometry", crs = 4326)

```

```{r, create test data}
library(tibble)

test_df <- tibble(
  date = as.POSIXct(c(
    "2026-03-28 10:29:34","2026-03-28 11:02:11","2026-03-28 11:45:03",
    "2026-03-28 12:10:55","2026-03-28 13:22:41","2026-03-28 14:05:18",
    "2026-03-28 14:48:50","2026-03-28 15:30:22","2026-03-28 16:12:09",
    "2026-03-28 16:55:44"
  )),
  start_time = date,
  species = c(
    "sperm_whale","common_dolphin","striped_dolphin",
    "bottlenose_dolphin","sperm_whale","pilot_whale",
    "common_dolphin","striped_dolphin","bottlenose_dolphin",
    "sperm_whale"
  ),
  numb_indiv = c(10, 25, 40, 12, 8, 15, 30, 22, 9, 6),
  end_time = start_time + sample(60:600, 10, replace = TRUE),
  
  behaviour = c(
    '{"foraging","jumping","spy_hopping"}',
    '{"travelling","bow_riding"}',
    '{"feeding","socializing"}',
    '{"resting","slow_swimming"}',
    '{"deep_diving","foraging"}',
    '{"socializing","logging"}',
    '{"bow_riding","jumping"}',
    '{"feeding","fast_swimming"}',
    '{"resting","spy_hopping"}',
    '{"deep_diving","foraging"}'
  ),
  
  UUID = c(
    "{042f70ba-fffd-491d-82a9-c5ea3cb1a8b4}",
    "{a12c70ba-fffd-491d-82a9-c5ea3cb1a8b5}",
    "{b23d70ba-fffd-491d-82a9-c5ea3cb1a8b6}",
    "{c34e70ba-fffd-491d-82a9-c5ea3cb1a8b7}",
    "{d45f70ba-fffd-491d-82a9-c5ea3cb1a8b8}",
    "{e56g70ba-fffd-491d-82a9-c5ea3cb1a8b9}",
    "{f67h70ba-fffd-491d-82a9-c5ea3cb1a8c0}",
    "{g78i70ba-fffd-491d-82a9-c5ea3cb1a8c1}",
    "{h89j70ba-fffd-491d-82a9-c5ea3cb1a8c2}",
    "{i90k70ba-fffd-491d-82a9-c5ea3cb1a8c3}"
  ),
  
  id = sample(1:5, 10, replace = TRUE),
  session_id = sample(1:3, 10, replace = TRUE),
  observer = c("SG","AB","SG","LM","SG","AB","LM","SG","AB","SG"),
  angle = sample(0:180, 10),
  distance = sample(10:500, 10),
  
  geometry = c(
    "POINT (-5.354597 36.1103)",
    "POINT (-5.360112 36.1150)",
    "POINT (-5.348900 36.1087)",
    "POINT (-5.352300 36.1125)",
    "POINT (-5.355800 36.1099)",
    "POINT (-5.349200 36.1133)",
    "POINT (-5.353700 36.1110)",
    "POINT (-5.347800 36.1075)",
    "POINT (-5.351500 36.1142)",
    "POINT (-5.356200 36.1108)"
  )
)

test_sf <- test_df %>% 
  st_as_sf(wkt = "geometry", crs = 4326)

# Cleaning data for behavioural analysis
df_clean <- test_sf %>%
  mutate(
    behaviour = str_remove_all(behaviour, '[\\{\\}"]')
  )
df_long <- df_clean %>%
  separate_rows(behaviour, sep = ",")

```

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")


bbox <- st_bbox(test_sf)
```

# Mapping



```{r}
xlims <- c(bbox["xmin"], bbox["xmax"])
ylims <- c(bbox["ymin"], bbox["ymax"])

map <- ggplot(survey_data)+
  # annotation_map_tile(type = "cartolight") +
 geom_sf(data = world,
   fill = "grey90",
   color = "grey70"
 ) +
  geom_sf(aes(color = species), size = 2)+
  coord_sf(xlim = xlims, ylim = ylims) +
  theme_minimal()
map

bar <- survey_data %>% 
  ggplot() +
  geom_bar(aes(x = species, fill = species))

# Use patchwork to order graphs
map / bar



survey_data %>% 
  ggplot() +
  geom_sf(data = world,
   fill = "grey90",
   color = "grey70"
 ) +
  geom_sf(aes(color = species))
  
  
```

