---
title: "Cetacean Spatial Distribution in the British Gibraltar Territorial Waters: A Systematic Baseline from Land-based Distance Sampling"
author: "Simon Gendrisch"
keywords: [Cetacean, Delphinus delphis, Gibraltar, Cetacean Distribution, Land-based Surveys, Distance Sampling, Marine Mammal Conservation, Kernel Density Estimation]

format: 

  typst:
        number-sections: true
        template-partials: 
          - typst/typst-show.typ
          - typst/journal/typst-template.typ
        output-file: M8.2_JournalArticle_206708
        citeproc: true
bibliography: refs.bib
csl: "SoMESHarvard.csl"

---


# Abstract{.unnumbered}

{{< include ./journal_chapters/j_abstract.qmd >}}

{{< pagebreak >}}

# Introduction

{{< include ./journal_chapters/j_intro.qmd >}}


{{< pagebreak >}}

# Methods {#methods-sec}

{{< include ./journal_chapters/j_methods.qmd >}}


{{< pagebreak >}}

# Results

{{< include ./journal_chapters/j_results.qmd >}}

{{< pagebreak >}}

# Discussion

{{< include ./journal_chapters/j_discussion.qmd >}}

{{< pagebreak >}}

```{=typst}
#[
```

# Acknowledgements{.unnumbered}

{{< include ./journal_chapters/j_acknowl.qmd >}}

# Generative AI (GenAI) Use{.unnumbered}
Generative AI was used to help with the structuring, and scientific writing of this work. It was also used to troubleshoot analysis and setup code. See Declaration of Originality and use of Gen AI for more details.

# Conflict of Interest{.unnumbered}
The authors declare that the research was conducted in the absence of any commercial or financial relationships that could be construed as a potential conflict of interest.

# Supplementary Material{.unnumbered}
Please see Supplementary Material with Appendices for further information related to this study.

{{< pagebreak >}}

# Science Communication output

{{< include ./chapters/comms.qmd >}}

{{< pagebreak >}}



# References
::: {#refs}
:::

```{=typst}
] <no-wc>
```


